// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: token/events.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventRewardDistribution struct {
	Address string         `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Delta   types.DecProto `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta"`
	Reward  types.Coin     `protobuf:"bytes,3,opt,name=reward,proto3" json:"reward"`
}

func (m *EventRewardDistribution) Reset()         { *m = EventRewardDistribution{} }
func (m *EventRewardDistribution) String() string { return proto.CompactTextString(m) }
func (*EventRewardDistribution) ProtoMessage()    {}
func (*EventRewardDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_18594780bd6d607c, []int{0}
}
func (m *EventRewardDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRewardDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRewardDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRewardDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRewardDistribution.Merge(m, src)
}
func (m *EventRewardDistribution) XXX_Size() int {
	return m.Size()
}
func (m *EventRewardDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRewardDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_EventRewardDistribution proto.InternalMessageInfo

func (m *EventRewardDistribution) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventRewardDistribution) GetDelta() types.DecProto {
	if m != nil {
		return m.Delta
	}
	return types.DecProto{}
}

func (m *EventRewardDistribution) GetReward() types.Coin {
	if m != nil {
		return m.Reward
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*EventRewardDistribution)(nil), "token.EventRewardDistribution")
}

func init() { proto.RegisterFile("token/events.proto", fileDescriptor_18594780bd6d607c) }

var fileDescriptor_18594780bd6d607c = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0xa0, 0x45, 0x84, 0x2d, 0x42, 0x22, 0x54, 0xc2, 0x54, 0x4c, 0x1d, 0xc0, 0x56,
	0x61, 0x40, 0xac, 0x25, 0x30, 0xa3, 0x8c, 0x6c, 0x49, 0x7c, 0x0a, 0x16, 0xd4, 0x57, 0xd9, 0xd7,
	0x02, 0x6f, 0xc1, 0x5b, 0xf0, 0x2a, 0x1d, 0x3b, 0x32, 0x21, 0x94, 0xbc, 0x08, 0x8a, 0x1d, 0xb6,
	0x6e, 0xe7, 0xff, 0xf7, 0xe7, 0x4f, 0xbe, 0x38, 0x21, 0x7c, 0x01, 0x23, 0x61, 0x05, 0x86, 0x9c,
	0x58, 0x58, 0x24, 0x4c, 0x06, 0x3e, 0x1b, 0x1d, 0xd5, 0x58, 0xa3, 0x4f, 0x64, 0x37, 0x85, 0x72,
	0xc4, 0x2b, 0x74, 0x73, 0x74, 0xb2, 0x2c, 0x1c, 0xc8, 0xd5, 0xb4, 0x04, 0x2a, 0xa6, 0xb2, 0x42,
	0x6d, 0x42, 0x7f, 0xfe, 0xc5, 0xe2, 0xe3, 0xfb, 0xee, 0xb5, 0x1c, 0xde, 0x0a, 0xab, 0x32, 0xed,
	0xc8, 0xea, 0x72, 0x49, 0x1a, 0x4d, 0x92, 0xc6, 0xfb, 0x85, 0x52, 0x16, 0x9c, 0x4b, 0xd9, 0x98,
	0x4d, 0x0e, 0xf2, 0xff, 0x63, 0x72, 0x1b, 0x0f, 0x14, 0xbc, 0x52, 0x91, 0xee, 0x8c, 0xd9, 0xe4,
	0xf0, 0xea, 0x54, 0x04, 0x8b, 0xe8, 0x2c, 0xa2, 0xb7, 0x88, 0x0c, 0xaa, 0xc7, 0xce, 0x31, 0xdb,
	0x5b, 0xff, 0x9c, 0x45, 0x79, 0x20, 0x92, 0x9b, 0x78, 0x68, 0xbd, 0x2a, 0xdd, 0xf5, 0xec, 0xc9,
	0x56, 0xf6, 0x0e, 0xb5, 0xe9, 0xb9, 0xfe, 0xfa, 0xec, 0x61, 0xdd, 0x70, 0xb6, 0x69, 0x38, 0xfb,
	0x6d, 0x38, 0xfb, 0x6c, 0x79, 0xb4, 0x69, 0x79, 0xf4, 0xdd, 0xf2, 0xe8, 0xe9, 0xa2, 0xd6, 0xf4,
	0xbc, 0x2c, 0x45, 0x85, 0x73, 0x99, 0x41, 0x05, 0x86, 0xec, 0xa5, 0x01, 0x92, 0x2a, 0xcc, 0xf2,
	0x5d, 0x86, 0xad, 0xd1, 0xc7, 0x02, 0x5c, 0x39, 0xf4, 0x1f, 0xbf, 0xfe, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xd6, 0x63, 0xee, 0xf8, 0x4b, 0x01, 0x00, 0x00,
}

func (m *EventRewardDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRewardDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRewardDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Reward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Delta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventRewardDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.Delta.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.Reward.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventRewardDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRewardDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRewardDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Delta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
